MODULE MOD_ATTEN

  USE NRTYPE    , ONLY: WP
  USE MOD_CONST , ONLY: N_FREQ, I2N_FREQ1
  IMPLICIT NONE

  REAL   (WP), DIMENSION(N_FREQ,I2N_FREQ1) :: FJJ, FJK
  COMPLEX(WP), DIMENSION(N_FREQ,I2N_FREQ1) :: CF      
  REAL   (WP), DIMENSION(  N_FREQ)         :: Y, B, P, FRJ, PFP21, PF21
  REAL   (WP), DIMENSION(  N_FREQ, N_FREQ) :: A                     
  REAL   (WP), DIMENSION(I2N_FREQ1)        :: Q, PLO, FRK

  INTERFACE

    SUBROUTINE     QYLSM(QQ,YY)
      USE NRTYPE   , ONLY: WP
      USE MOD_CONST, ONLY: N_FREQ, I2N_FREQ1
      IMPLICIT NONE
      REAL(WP), DIMENSION (  N_FREQ ), INTENT(INOUT) :: YY
      REAL(WP), DIMENSION (I2N_FREQ1), INTENT(INOUT) :: QQ
    END SUBROUTINE QYLSM

  END INTERFACE

END MODULE MOD_ATTEN