MODULE MOD_INTERFACES

IMPLICIT NONE

INTERFACE

  SUBROUTINE     ADD_NEW_CELL_TYPE
  END SUBROUTINE ADD_NEW_CELL_TYPE

  SUBROUTINE     ALLOCATE_ARRAYS
  END SUBROUTINE ALLOCATE_ARRAYS

  SUBROUTINE     FILTER
  END SUBROUTINE FILTER

  SUBROUTINE     FIND_MAX_DEPTH
  END SUBROUTINE FIND_MAX_DEPTH

  FUNCTION     FUNC_MU_LA_RHO(X,Z)
    USE NRTYPE              , ONLY: WP
    IMPLICIT NONE
    REAL(WP), INTENT(IN) :: X,Z
    REAL(WP)             :: FUNC_MU_LA_RHO(17)
  END FUNCTION FUNC_MU_LA_RHO


  FUNCTION     GET_LAYER (X,Z)
    USE NRTYPE   , ONLY: WP
    IMPLICIT NONE
    REAL(WP), INTENT(IN) :: X, Z
    INTEGER              :: GET_LAYER
  END FUNCTION GET_LAYER

  FUNCTION     GETDEPTH (X,NINF)
    USE NRTYPE   , ONLY: WP
    IMPLICIT NONE
    REAL(WP),INTENT(IN) :: X
    integer, intent(in) :: NINF
    REAL(WP)            :: GETDEPTH
  END FUNCTION GETDEPTH

  FUNCTION     GET_FD_CELL_INDEX()
    INTEGER :: GET_FD_CELL_INDEX
  END FUNCTION GET_FD_CELL_INDEX

  FUNCTION     INT3D (II,LI,FIELD)
    USE NRTYPE         , ONLY: WP
    IMPLICIT NONE
    INTEGER, INTENT(IN)  :: II, LI
    REAL(WP)             :: INT3D
    REAL(WP), DIMENSION(:,:), INTENT(INOUT) :: FIELD
  END FUNCTION INT3D

  FUNCTION     IS_IN_1D_MEDIUM(X,Z)
    USE NRTYPE        , ONLY: WP
    IMPLICIT NONE
    REAL(WP), INTENT(IN) :: X,Z
    LOGICAL              :: IS_IN_1D_MEDIUM
  END FUNCTION IS_IN_1D_MEDIUM

  SUBROUTINE     MODEL_LIN
  END SUBROUTINE MODEL_LIN

  SUBROUTINE     PARAMETERIZATION
  END SUBROUTINE PARAMETERIZATION

  SUBROUTINE     PREPARE_FINE_PAR (MXT, L, H, Z0)
    USE NRTYPE         , ONLY: SP
    IMPLICIT NONE
    INTEGER , INTENT(IN) :: MXT, L
    REAL(SP), INTENT(IN) :: H, Z0
  END SUBROUTINE PREPARE_FINE_PAR

  SUBROUTINE     PRINT_INFO
  END SUBROUTINE PRINT_INFO

  SUBROUTINE     SETPARAMS
  END SUBROUTINE SETPARAMS

  LOGICAL FUNCTION TEST_CELLS( LAST_CELL, CELL )
    USE NRTYPE              , ONLY: WP, SP
    USE MOD_CONST           , ONLY: N_E_PAR
    IMPLICIT NONE
    INTEGER ,                     INTENT(IN) :: LAST_CELL
    REAL(SP), DIMENSION(N_E_PAR), INTENT(IN) :: CELL
  END FUNCTION TEST_CELLS


  SUBROUTINE     TEST_PARAMETERS
  END SUBROUTINE TEST_PARAMETERS

  SUBROUTINE     WRITE_PARAM
  END SUBROUTINE WRITE_PARAM

END INTERFACE

END MODULE MOD_INTERFACES
